//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFTP_Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OFTP_Client.Resources.CodeNames", typeof(CodeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 502.
        /// </summary>
        internal static string AcceptedIncomingConnection {
            get {
                return ResourceManager.GetString("AcceptedIncomingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 602.
        /// </summary>
        internal static string AcceptFileTransmission {
            get {
                return ResourceManager.GetString("AcceptFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 107.
        /// </summary>
        internal static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501.
        /// </summary>
        internal static string AskUserForConnection {
            get {
                return ResourceManager.GetString("AskUserForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 601.
        /// </summary>
        internal static string BeginFileTransmission {
            get {
                return ResourceManager.GetString("BeginFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        internal static string CorrectLoginData {
            get {
                return ResourceManager.GetString("CorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.
        /// </summary>
        internal static string CorrectRegisterData {
            get {
                return ResourceManager.GetString("CorrectRegisterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 504.
        /// </summary>
        internal static string DisconnectFromClient {
            get {
                return ResourceManager.GetString("DisconnectFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 604.
        /// </summary>
        internal static string EndFileTransmission {
            get {
                return ResourceManager.GetString("EndFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 606.
        /// </summary>
        internal static string FileLength {
            get {
                return ResourceManager.GetString("FileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 106.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 607.
        /// </summary>
        internal static string NextDataLength {
            get {
                return ResourceManager.GetString("NextDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 605.
        /// </summary>
        internal static string NextPartialData {
            get {
                return ResourceManager.GetString("NextPartialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 608.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 201.
        /// </summary>
        internal static string RegistrationLoginExists {
            get {
                return ResourceManager.GetString("RegistrationLoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 202.
        /// </summary>
        internal static string RegistrationPasswordWrong {
            get {
                return ResourceManager.GetString("RegistrationPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503.
        /// </summary>
        internal static string RejectedIncomingConnection {
            get {
                return ResourceManager.GetString("RejectedIncomingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603.
        /// </summary>
        internal static string RejectFileTransmission {
            get {
                return ResourceManager.GetString("RejectFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108.
        /// </summary>
        internal static string UserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("UserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string WrongLoginData {
            get {
                return ResourceManager.GetString("WrongLoginData", resourceCulture);
            }
        }
    }
}
