//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFTP_Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileTransmissionCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileTransmissionCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OFTP_Client.Resources.FileTransmissionCodes", typeof(FileTransmissionCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 602.
        /// </summary>
        internal static string AcceptFileTransmission {
            get {
                return ResourceManager.GetString("AcceptFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 601.
        /// </summary>
        internal static string BeginFileTransmission {
            get {
                return ResourceManager.GetString("BeginFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 604.
        /// </summary>
        internal static string EndFileTransmission {
            get {
                return ResourceManager.GetString("EndFileTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 606.
        /// </summary>
        internal static string FileLength {
            get {
                return ResourceManager.GetString("FileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 608.
        /// </summary>
        internal static string FileTransmissionInterrupted {
            get {
                return ResourceManager.GetString("FileTransmissionInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 605.
        /// </summary>
        internal static string NextPartialData {
            get {
                return ResourceManager.GetString("NextPartialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 607.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603.
        /// </summary>
        internal static string RejectFileTransmission {
            get {
                return ResourceManager.GetString("RejectFileTransmission", resourceCulture);
            }
        }
    }
}
